### ISSUE TITLE
Docker image for dmarc-metrics-exporter

### ISSUE THREAD

**Issue by JamborJan** [jgosmann/dmarc-metrics-exporter#2]
Are there any plans for a Docker Image of your dmarc-metrics-exporter? Would be nice to have that available in a containerized environment as a piece of the microservice puzzle.

**Comment by JamborJan** [comment]
I did test some things, see: https://github.com/jgosmann/dmarc-metrics-exporter/pull/3

But I'm getting the following errors. Do you have any ideas how to solve them? I think they have nothing to do with the docker image but with my settings. But I don't know where the error could be.

```
INFO:     Uvicorn running on http://127.0.0.1:9797 (Press CTRL+C to quit),
Task exception was never retrieved,
future: <Task finished name='Task-7' coro=<IMAP4ClientProtocol.welcome() done, defined at /home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py:305> exception=TypeError("'Condition' object is not iterable")>,
Traceback (most recent call last):,
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 308, in wrapper,
    with (yield from self.state_condition):,
TypeError: 'Condition' object is not iterable,
Error during IMAP queue polling.,
Traceback (most recent call last):,
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/dmarc_metrics_exporter/imap_queue.py", line 53, in _consume,
    async with ImapClient(self.connection, self.timeout_seconds) as client:,
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/dmarc_metrics_exporter/imap_queue.py", line 89, in __aenter__,
    await self._client.wait_hello_from_server(),
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 710, in wait_hello_from_server,
    yield from asyncio.wait_for(self.protocol.wait('AUTH|NONAUTH'), self.timeout),
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for,
    return fut.result(),
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 618, in wait,
    with (yield from self.state_condition):,
TypeError: 'Condition' object is not iterable,
Task exception was never retrieved,
future: <Task finished name='Task-10' coro=<IMAP4ClientProtocol.welcome() done, defined at /home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py:305> exception=TypeError("'Condition' object is not iterable")>,
Traceback (most recent call last):,
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 308, in wrapper,
    with (yield from self.state_condition):,
TypeError: 'Condition' object is not iterable,
Task exception was never retrieved,
future: <Task finished name='Task-11' coro=<IMAP4ClientProtocol.welcome() done, defined at /home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py:305> exception=TypeError("'Condition' object is not iterable")>,
Traceback (most recent call last):,
  File "/home/dmarc-metrics/.local/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 308, in wrapper,
    with (yield from self.state_condition):,
TypeError: 'Condition' object is not iterable
```
