### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by DeolTito** [jgosmann/dmarc-metrics-exporter#26]
Hello,

While trying to exxport DMARC report on a dockerized container, I'm getting the error below.

=========

INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9797 (Press CTRL+C to quit)
Error during IMAP queue polling.
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 59, in _consume
    async for uid, msg in client.fetch(1, msg_count):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 125, in fetch
    match = mail_header_regex.match(line)
TypeError: cannot use a string pattern on a bytes-like object
INFO:     172.22.0.4:35308 - "GET /metrics HTTP/1.1" 200 OK
INFO:     Shutting down
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/app.py", line 79, in run
    self._save_metrics()
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/app.py", line 88, in _save_metrics
    self.metrics_persister.save(metrics)
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/metrics_persister.py", line 55, in save
    with open(self.path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/var/lib/dmarc-metrics-exporter/metrics.db'

===========

**Comment by DeolTito** [comment]
Hello,

I've fixed this error, but currently I'm encountering the error mentioned below

ImportError: ('UID MOVE', 'NO', [b'Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).'])

**Comment by jgosmann** [comment]
Please provide the following additional information:
* Python version
* dmarc-metrics-exporter version
* full stack trace of the error

**Comment by DeolTito** [comment]
Please take a look at the details mentioned below

Python 2.7.17 (Host machine)
Python 3.7.12 (Dmarc-exporter container)
dmarc-metrics-exporter:0.4.1 - Dmarc-exporter version

The one mentioned below is the error I'm encountering while running it

===========

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 68, in _consume
    await client.uid_move(uid, self.folders.done)
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 154, in uid_move
    self._client.uid("move", str(uid), destination),
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 102, in _check
    raise ImportError(command, res, data)
ImportError: ('UID MOVE', 'NO', [b'Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).'])
Error during IMAP queue polling.
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/app.py", line 96, in run
    self._save_metrics()
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/app.py", line 105, in _save_metrics
    self.metrics_persister.save(metrics)
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/metrics_persister.py", line 55, in save
    with open(self.path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: '/var/lib/dmarc-metrics-exporter/metrics.db'

===========

I've connected my email account in BlueHost with it and it seem to fetch the report. However, it just fetches the last mail in the inbox but not the other ones. Also, this particular error is seen in the docker logs.

**Comment by DeolTito** [comment]
Why does it fetch the report from the very first mail only?

 I've around 10 mails with DMARC reports arrived on my inbox. Is there any way fetch all those mail report at once?

**Comment by jgosmann** [comment]
Are you using the default `folders` configuration? From the error reported by the server it seems, the folder names might need to be prefixed with `INBOX.`, e.g.:
```json
{
    "folders": {
        "done": "INBOX.Archive",
        "error": "INBOX.Invalid"
    }
}
```

Can you also check whether those folders actually exist in the mailbox? They should be created automatically by dmarc-metrics-exporter, though.

There's also a permission error. You need to ensure that `/var/lib/dmarc-metrics-exporter/metrics.db` is writable.

> Why does it fetch the report from the very first mail only?

I suppose that because it fails to move the message out of the inbox, no further messages are processed.

**Comment by DeolTito** [comment]
>> Are you using the default folders configuration?

Yes, I was using the default folders. I'll try switching to the ones you've mentioned in the example. And yes, Archive folder is already available in the mailbox. 

Regarding the metrics.db, I was not able to view this particular file under the path (/var/lib/dmarc-metrics-exporter/) in container. Should I create a file named metrics.db in the host machine and map it to the container?

 I was under the impression that this metrics.db will be automatically created once the container is online. However, it wasn't available. Please let me know your opinion on this.

**Comment by DeolTito** [comment]
I tried changing the folder names to tone mentioned below and the container is not being started now.

    },
    "folders": {
        "inbox": "Inbox",
        "done" : "Inbox.archive",
        "error": "Inbox.Invalid"

Please take a look at the error seen in the docker logs.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/__main__.py", line 5, in <module>
    main(sys.argv[1:])
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/app.py", line 56, in main
    asyncio.run(app.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/app.py", line 89, in run
    self.exporter = self.exporter_cls(self.metrics_persister.load())
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/metrics_persister.py", line 50, in load
    return JSONSerializer.deserialize(DmarcMetricsCollection, json.load(f))
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DeolTito** [comment]
Sorry, I'm a bit confused on this step. While creating the container, should we create a file named metrics.db under the path /var/lib/dmarc-metrics-exporter in our host machine and map it to the container?

I'm using Roundcube as the mail client, under that we won't be to create the folder with special characters. I believe due to that reason the folder names such Inbox.archive is not being created and the read mails aren't moved to it. Is there any workaround for that?

**Comment by jgosmann** [comment]
> Sorry, I'm a bit confused on this step. While creating the container, should we create a file named metrics.db under the path /var/lib/dmarc-metrics-exporter in our host machine and map it to the container?

The file should be created by dmarc-metrics-exporter. But you likely want to map it from the host machine into the container, so that it is persisted between restarts of the container.

> I'm using Roundcube as the mail client

The mail client should be irrelevant. The IMAP server might be a problem, though.

> I believe due to that reason the folder names such Inbox.archive is not being created and the read mails aren't moved to it. Is there any workaround for that?

You can configure any folder names you like if they work for you. However, the defaults don't contain special characters, and in one of the previous stack traces the server said "Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX."

**Comment by jgosmann** [comment]
Closing this as stale, feel free to reopen if you still have problems.
