### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_ssl'

### ISSUE THREAD

**Issue by valentinomariotto** [jgosmann/dmarc-metrics-exporter#47]
Hi,
I'm running the docker-compose environment and I'm getting this error in the logs:
`TypeError: __init__() got an unexpected keyword argument 'use_ssl'`

My dmarc-metrics-exporter.json looks like this:

```
{
    "listen_addr": "0.0.0.0",
    "port": 9711,
    "imap": {
        "host": "emailproxy",
        "port": 1993,
        "username": "dmarc@mydomain.com",
        "password": "mypassword",
        "use_ssl": false,
        "verify_certificate": false
    },
    "folders": {
        "inbox": "INBOX",
        "done": "Archive",
        "error": "Invalid"
    },
    "storage_path": "/var/lib/dmarc-metrics-exporter",
    "poll_interval_seconds": 60,
    "deduplication_max_seconds": 604800,
    "logging": {
        "handlers": {
            "default": {
                "class": "logging.StreamHandler",
                "formatter": "json"
            }
        },
        "loggers": {
            "uvicorn.access": {
                "propagate": false
            }
        }
    }
}
```

Setting aside the issue that basic auth is not available in 365 anymore, the error seems to suggest a syntax error

**Comment by valentinomariotto** [comment]
it runs when removing these options:
        "use_ssl": false,
        "verify_certificate": false

But is there a way to ensure that the IMAP client will NOT use SSL?

**Comment by valentinomariotto** [comment]
I added SSL certs to the proxy to which this client is connecting, and now I get:

```
Error during IMAP queue polling.
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 59, in _consume
    async for uid, msg in client.fetch(1, msg_count):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_queue.py", line 125, in fetch
    match = mail_header_regex.match(line)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by valentinomariotto** [comment]
correcting the docker-compose script to use version 1.0.0 rather than version 0.3.0 fixed the issues. 
Please update the documentation
Thank you for this useful software!

**Comment by jgosmann** [comment]
Reopening as a reminder to update the documentation.
